name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        apt-get install postgresql postgresql-contrib
        shards install

    - name: Run tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: 5432
      run: crystal spec
